/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CostSheetsRouteImport } from './routes/cost-sheets'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MailboxesRouteImport } from './routes/mailboxes'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as PrequalificationsRouteImport } from './routes/prequalifications'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as CostSheetsIdRouteImport } from './routes/cost-sheets.$id'
import { Route as QuotationsIdRouteImport } from './routes/quotations.$id'
import { Route as ApiAttachmentsUploadRouteImport } from './routes/api/attachments/upload'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'
import { Route as ApiOauthGoogleStartRouteImport } from './routes/api/oauth/google/start'
import { Route as ApiOauthMicrosoftCallbackRouteImport } from './routes/api/oauth/microsoft/callback'
import { Route as ApiOauthMicrosoftStartRouteImport } from './routes/api/oauth/microsoft/start'
import { Route as ApiPublicTClickRouteImport } from './routes/api/public/t/click'
import { Route as ApiPublicTOpenRouteImport } from './routes/api/public/t/open'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CostSheetsRoute = CostSheetsRouteImport.update({
  id: '/cost-sheets',
  path: '/cost-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesRoute = MailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrequalificationsRoute = PrequalificationsRouteImport.update({
  id: '/prequalifications',
  path: '/prequalifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const CostSheetsIdRoute = CostSheetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CostSheetsRoute,
} as any)
const QuotationsIdRoute = QuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuotationsRoute,
} as any)
const ApiAttachmentsUploadRoute = ApiAttachmentsUploadRouteImport.update({
  id: '/api/attachments/upload',
  path: '/api/attachments/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleStartRoute = ApiOauthGoogleStartRouteImport.update({
  id: '/api/oauth/google/start',
  path: '/api/oauth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthMicrosoftCallbackRoute =
  ApiOauthMicrosoftCallbackRouteImport.update({
    id: '/api/oauth/microsoft/callback',
    path: '/api/oauth/microsoft/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMicrosoftStartRoute = ApiOauthMicrosoftStartRouteImport.update({
  id: '/api/oauth/microsoft/start',
  path: '/api/oauth/microsoft/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTClickRoute = ApiPublicTClickRouteImport.update({
  id: '/api/public/t/click',
  path: '/api/public/t/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTOpenRoute = ApiPublicTOpenRouteImport.update({
  id: '/api/public/t/open',
  path: '/api/public/t/open',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/bids': typeof BidsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/cost-sheets': typeof CostSheetsRouteWithChildren
  '/deals': typeof DealsRoute
  '/inbox': typeof InboxRoute
  '/mailboxes': typeof MailboxesRoute
  '/marketing': typeof MarketingRoute
  '/prequalifications': typeof PrequalificationsRoute
  '/prospects': typeof ProspectsRoute
  '/quotations': typeof QuotationsRouteWithChildren
  '/campaigns/$id': typeof CampaignsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/cost-sheets/$id': typeof CostSheetsIdRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
  '/api/oauth/microsoft/callback': typeof ApiOauthMicrosoftCallbackRoute
  '/api/oauth/microsoft/start': typeof ApiOauthMicrosoftStartRoute
  '/api/public/t/click': typeof ApiPublicTClickRoute
  '/api/public/t/open': typeof ApiPublicTOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/bids': typeof BidsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/cost-sheets': typeof CostSheetsRouteWithChildren
  '/deals': typeof DealsRoute
  '/inbox': typeof InboxRoute
  '/mailboxes': typeof MailboxesRoute
  '/marketing': typeof MarketingRoute
  '/prequalifications': typeof PrequalificationsRoute
  '/prospects': typeof ProspectsRoute
  '/quotations': typeof QuotationsRouteWithChildren
  '/campaigns/$id': typeof CampaignsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/cost-sheets/$id': typeof CostSheetsIdRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
  '/api/oauth/microsoft/callback': typeof ApiOauthMicrosoftCallbackRoute
  '/api/oauth/microsoft/start': typeof ApiOauthMicrosoftStartRoute
  '/api/public/t/click': typeof ApiPublicTClickRoute
  '/api/public/t/open': typeof ApiPublicTOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/bids': typeof BidsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/cost-sheets': typeof CostSheetsRouteWithChildren
  '/deals': typeof DealsRoute
  '/inbox': typeof InboxRoute
  '/mailboxes': typeof MailboxesRoute
  '/marketing': typeof MarketingRoute
  '/prequalifications': typeof PrequalificationsRoute
  '/prospects': typeof ProspectsRoute
  '/quotations': typeof QuotationsRouteWithChildren
  '/campaigns/$id': typeof CampaignsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/cost-sheets/$id': typeof CostSheetsIdRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
  '/api/oauth/microsoft/callback': typeof ApiOauthMicrosoftCallbackRoute
  '/api/oauth/microsoft/start': typeof ApiOauthMicrosoftStartRoute
  '/api/public/t/click': typeof ApiPublicTClickRoute
  '/api/public/t/open': typeof ApiPublicTOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreements'
    | '/bids'
    | '/clients'
    | '/cost-sheets'
    | '/deals'
    | '/inbox'
    | '/mailboxes'
    | '/marketing'
    | '/prequalifications'
    | '/prospects'
    | '/quotations'
    | '/campaigns/$id'
    | '/clients/$id'
    | '/cost-sheets/$id'
    | '/quotations/$id'
    | '/campaigns/'
    | '/api/attachments/upload'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
    | '/api/oauth/microsoft/callback'
    | '/api/oauth/microsoft/start'
    | '/api/public/t/click'
    | '/api/public/t/open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreements'
    | '/bids'
    | '/clients'
    | '/cost-sheets'
    | '/deals'
    | '/inbox'
    | '/mailboxes'
    | '/marketing'
    | '/prequalifications'
    | '/prospects'
    | '/quotations'
    | '/campaigns/$id'
    | '/clients/$id'
    | '/cost-sheets/$id'
    | '/quotations/$id'
    | '/campaigns'
    | '/api/attachments/upload'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
    | '/api/oauth/microsoft/callback'
    | '/api/oauth/microsoft/start'
    | '/api/public/t/click'
    | '/api/public/t/open'
  id:
    | '__root__'
    | '/'
    | '/agreements'
    | '/bids'
    | '/clients'
    | '/cost-sheets'
    | '/deals'
    | '/inbox'
    | '/mailboxes'
    | '/marketing'
    | '/prequalifications'
    | '/prospects'
    | '/quotations'
    | '/campaigns/$id'
    | '/clients/$id'
    | '/cost-sheets/$id'
    | '/quotations/$id'
    | '/campaigns/'
    | '/api/attachments/upload'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
    | '/api/oauth/microsoft/callback'
    | '/api/oauth/microsoft/start'
    | '/api/public/t/click'
    | '/api/public/t/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgreementsRoute: typeof AgreementsRoute
  BidsRoute: typeof BidsRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  CostSheetsRoute: typeof CostSheetsRouteWithChildren
  DealsRoute: typeof DealsRoute
  InboxRoute: typeof InboxRoute
  MailboxesRoute: typeof MailboxesRoute
  MarketingRoute: typeof MarketingRoute
  PrequalificationsRoute: typeof PrequalificationsRoute
  ProspectsRoute: typeof ProspectsRoute
  QuotationsRoute: typeof QuotationsRouteWithChildren
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ApiAttachmentsUploadRoute: typeof ApiAttachmentsUploadRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthGoogleStartRoute: typeof ApiOauthGoogleStartRoute
  ApiOauthMicrosoftCallbackRoute: typeof ApiOauthMicrosoftCallbackRoute
  ApiOauthMicrosoftStartRoute: typeof ApiOauthMicrosoftStartRoute
  ApiPublicTClickRoute: typeof ApiPublicTClickRoute
  ApiPublicTOpenRoute: typeof ApiPublicTOpenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-sheets': {
      id: '/cost-sheets'
      path: '/cost-sheets'
      fullPath: '/cost-sheets'
      preLoaderRoute: typeof CostSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes': {
      id: '/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof MailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prequalifications': {
      id: '/prequalifications'
      path: '/prequalifications'
      fullPath: '/prequalifications'
      preLoaderRoute: typeof PrequalificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/cost-sheets/$id': {
      id: '/cost-sheets/$id'
      path: '/$id'
      fullPath: '/cost-sheets/$id'
      preLoaderRoute: typeof CostSheetsIdRouteImport
      parentRoute: typeof CostSheetsRoute
    }
    '/quotations/$id': {
      id: '/quotations/$id'
      path: '/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof QuotationsIdRouteImport
      parentRoute: typeof QuotationsRoute
    }
    '/api/attachments/upload': {
      id: '/api/attachments/upload'
      path: '/api/attachments/upload'
      fullPath: '/api/attachments/upload'
      preLoaderRoute: typeof ApiAttachmentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/start': {
      id: '/api/oauth/google/start'
      path: '/api/oauth/google/start'
      fullPath: '/api/oauth/google/start'
      preLoaderRoute: typeof ApiOauthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/microsoft/callback': {
      id: '/api/oauth/microsoft/callback'
      path: '/api/oauth/microsoft/callback'
      fullPath: '/api/oauth/microsoft/callback'
      preLoaderRoute: typeof ApiOauthMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/microsoft/start': {
      id: '/api/oauth/microsoft/start'
      path: '/api/oauth/microsoft/start'
      fullPath: '/api/oauth/microsoft/start'
      preLoaderRoute: typeof ApiOauthMicrosoftStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/click': {
      id: '/api/public/t/click'
      path: '/api/public/t/click'
      fullPath: '/api/public/t/click'
      preLoaderRoute: typeof ApiPublicTClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/open': {
      id: '/api/public/t/open'
      path: '/api/public/t/open'
      fullPath: '/api/public/t/open'
      preLoaderRoute: typeof ApiPublicTOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface CostSheetsRouteChildren {
  CostSheetsIdRoute: typeof CostSheetsIdRoute
}

const CostSheetsRouteChildren: CostSheetsRouteChildren = {
  CostSheetsIdRoute: CostSheetsIdRoute,
}

const CostSheetsRouteWithChildren = CostSheetsRoute._addFileChildren(
  CostSheetsRouteChildren,
)

interface QuotationsRouteChildren {
  QuotationsIdRoute: typeof QuotationsIdRoute
}

const QuotationsRouteChildren: QuotationsRouteChildren = {
  QuotationsIdRoute: QuotationsIdRoute,
}

const QuotationsRouteWithChildren = QuotationsRoute._addFileChildren(
  QuotationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgreementsRoute: AgreementsRoute,
  BidsRoute: BidsRoute,
  ClientsRoute: ClientsRouteWithChildren,
  CostSheetsRoute: CostSheetsRouteWithChildren,
  DealsRoute: DealsRoute,
  InboxRoute: InboxRoute,
  MailboxesRoute: MailboxesRoute,
  MarketingRoute: MarketingRoute,
  PrequalificationsRoute: PrequalificationsRoute,
  ProspectsRoute: ProspectsRoute,
  QuotationsRoute: QuotationsRouteWithChildren,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ApiAttachmentsUploadRoute: ApiAttachmentsUploadRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthGoogleStartRoute: ApiOauthGoogleStartRoute,
  ApiOauthMicrosoftCallbackRoute: ApiOauthMicrosoftCallbackRoute,
  ApiOauthMicrosoftStartRoute: ApiOauthMicrosoftStartRoute,
  ApiPublicTClickRoute: ApiPublicTClickRoute,
  ApiPublicTOpenRoute: ApiPublicTOpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
