/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ApiPublicTClickRouteImport } from './routes/api/public/t/click'
import { Route as ApiPublicTOpenRouteImport } from './routes/api/public/t/open'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTClickRoute = ApiPublicTClickRouteImport.update({
  id: '/api/public/t/click',
  path: '/api/public/t/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTOpenRoute = ApiPublicTOpenRouteImport.update({
  id: '/api/public/t/open',
  path: '/api/public/t/open',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prospects': typeof ProspectsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/public/t/click': typeof ApiPublicTClickRoute
  '/api/public/t/open': typeof ApiPublicTOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prospects': typeof ProspectsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/api/public/t/click': typeof ApiPublicTClickRoute
  '/api/public/t/open': typeof ApiPublicTOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prospects': typeof ProspectsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/public/t/click': typeof ApiPublicTClickRoute
  '/api/public/t/open': typeof ApiPublicTOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prospects'
    | '/campaigns/$id'
    | '/campaigns/'
    | '/api/public/t/click'
    | '/api/public/t/open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prospects'
    | '/campaigns/$id'
    | '/campaigns'
    | '/api/public/t/click'
    | '/api/public/t/open'
  id:
    | '__root__'
    | '/'
    | '/prospects'
    | '/campaigns/$id'
    | '/campaigns/'
    | '/api/public/t/click'
    | '/api/public/t/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProspectsRoute: typeof ProspectsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ApiPublicTClickRoute: typeof ApiPublicTClickRoute
  ApiPublicTOpenRoute: typeof ApiPublicTOpenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/click': {
      id: '/api/public/t/click'
      path: '/api/public/t/click'
      fullPath: '/api/public/t/click'
      preLoaderRoute: typeof ApiPublicTClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/open': {
      id: '/api/public/t/open'
      path: '/api/public/t/open'
      fullPath: '/api/public/t/open'
      preLoaderRoute: typeof ApiPublicTOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProspectsRoute: ProspectsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ApiPublicTClickRoute: ApiPublicTClickRoute,
  ApiPublicTOpenRoute: ApiPublicTOpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
